// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR1Witvkw0Y7mAd1OqPy0Ov6ID_6iuGRo',
    appId: '1:639837271318:web:299721d561c9d744cd8c37',
    messagingSenderId: '639837271318',
    projectId: 'resala-65331',
    authDomain: 'resala-65331.firebaseapp.com',
    storageBucket: 'resala-65331.firebasestorage.app',
    measurementId: 'G-4RM2KTMMEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHltzl_9MlD1VfQLQIsz-CoaCJz_Q8wxs',
    appId: '1:639837271318:android:bc2a7e046eedeb85cd8c37',
    messagingSenderId: '639837271318',
    projectId: 'resala-65331',
    storageBucket: 'resala-65331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6YyzXRGaRQyVk0QQVqCN3XiwaDioY5J8',
    appId: '1:639837271318:ios:0bc3f600f2382a81cd8c37',
    messagingSenderId: '639837271318',
    projectId: 'resala-65331',
    storageBucket: 'resala-65331.firebasestorage.app',
    iosBundleId: 'com.example.resala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6YyzXRGaRQyVk0QQVqCN3XiwaDioY5J8',
    appId: '1:639837271318:ios:0bc3f600f2382a81cd8c37',
    messagingSenderId: '639837271318',
    projectId: 'resala-65331',
    storageBucket: 'resala-65331.firebasestorage.app',
    iosBundleId: 'com.example.resala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR1Witvkw0Y7mAd1OqPy0Ov6ID_6iuGRo',
    appId: '1:639837271318:web:91fe45ee694a3ca0cd8c37',
    messagingSenderId: '639837271318',
    projectId: 'resala-65331',
    authDomain: 'resala-65331.firebaseapp.com',
    storageBucket: 'resala-65331.firebasestorage.app',
    measurementId: 'G-MMZ2NB7TBQ',
  );

}